version: '3.9'

services:

  jupyter:
    platform: linux/x86_64
    build:
      context: ./docker
    ports:
     - "8888:8888"
    tty: true
    volumes:
      - './src:/work'
    networks:
      default:
      app_network:
        aliases:
          - python-dev

networks:
  app_network:
    external: true